### ISSUE TITLE
如果RGB图像三通道，做两次haar变换c会是48。通道数发生了改变，这不是与原先的三通道就不符了嘛？

### ISSUE THREAD

**Issue by Songxinlei** [JL-DY/MFDNet#1]
你好，麻烦问一下，请问如果RGB图像三通道，做两次haar变换c会是48。通道数发生了改变，这不是与原先的三通道就不符了嘛？这样的话，怎么解决呢

**Comment by JL-DY** [comment]
是的，一次haar变换会让通道增加4倍，就像我readme里说的一样，这篇论文还没有中，有些东西写的不是很清楚，所以这一块我就还是用的haar变换做下采样。由于我自身项目的原因，这个模型我是以单通道图像做的输入，不是可见光的三通道。

**Comment by Songxinlei** [comment]
这篇文章中了已经，Z. Liu, M. Jin, Y. Chen, H. Liu, C. Yang and H. Xiong, "Lightweight Network Towards Real-Time Image Denoising On Mobile Devices," 2023 IEEE International Conference on Image Processing (ICIP), Kuala Lumpur, Malaysia, 2023, pp. 2270-2274, doi: 10.1109/ICIP49359.2023.10222387.我是想着如果做两次harr变换，这样通道数增加那么多，参数量也会增加很多。轻量化程度上就有点压力了

**Comment by JL-DY** [comment]
哦哦哦，已经中了吗，不知道他代码现在有没有开源，如果开源了的话，可以试一试。
至于你说的参数量增加是不会的，haar变换是一种无损压缩方式，通道数增加了4倍，但是图像尺寸也会下降4倍，实际上使用反而会比大尺寸图像推理更快

**Comment by Songxinlei** [comment]
是的，已经中了的，不过代码好像还没开源。
原来是这样子，确实，下采样，图像尺寸大小也是降了下来。
好的，谢谢答疑啦~
